"""add property promotions

Revision ID: 0afe0368ad31
Revises: 50e9211a3680
Create Date: 2026-09-25 00:23:53.338951
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0afe0368ad31'
down_revision: Union[str, Sequence[str], None] = '50e9211a3680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('package', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_promotions_expires_at'), 'property_promotions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_property_promotions_id'), 'property_promotions', ['id'], unique=False)
    op.create_index(op.f('ix_property_promotions_payment_reference'), 'property_promotions', ['payment_reference'], unique=True)
    op.create_index(op.f('ix_property_promotions_payment_status'), 'property_promotions', ['payment_status'], unique=False)
    op.create_index(op.f('ix_property_promotions_property_id'), 'property_promotions', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_promotions_user_id'), 'property_promotions', ['user_id'], unique=False)
    op.add_column(
        'properties',
        sa.Column(
            'is_featured',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )
    op.add_column(
        'properties',
        sa.Column(
            'featured_until',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )
    op.create_index(op.f('ix_properties_featured_until'), 'properties', ['featured_until'], unique=False)
    op.create_index(op.f('ix_properties_is_featured'), 'properties', ['is_featured'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_is_featured'), table_name='properties')
    op.drop_index(op.f('ix_properties_featured_until'), table_name='properties')
    op.drop_column('properties', 'featured_until')
    op.drop_column('properties', 'is_featured')
    op.drop_index(op.f('ix_property_promotions_user_id'), table_name='property_promotions')
    op.drop_index(op.f('ix_property_promotions_property_id'), table_name='property_promotions')
    op.drop_index(op.f('ix_property_promotions_payment_status'), table_name='property_promotions')
    op.drop_index(op.f('ix_property_promotions_payment_reference'), table_name='property_promotions')
    op.drop_index(op.f('ix_property_promotions_id'), table_name='property_promotions')
    op.drop_index(op.f('ix_property_promotions_expires_at'), table_name='property_promotions')
    op.drop_table('property_promotions')
    # ### end Alembic commands ###