"""create landlord verification table

Revision ID: 2d9c4245039d
Revises: cc9412d6ace0
Create Date: 2026-08-25 14:47:11.492316
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9c4245039d'
down_revision: Union[str, Sequence[str], None] = 'cc9412d6ace0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlord_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('national_id_number', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landlord_verifications_id'), 'landlord_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_landlord_verifications_user_id'), 'landlord_verifications', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landlord_verifications_user_id'), table_name='landlord_verifications')
    op.drop_index(op.f('ix_landlord_verifications_id'), table_name='landlord_verifications')
    op.drop_table('landlord_verifications')
    # ### end Alembic commands ###