"""add mpesa payment tracking

Revision ID: 360d6e57493d
Revises: 0afe0368ad31
Create Date: 2026-09-25 00:56:14.123608
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '360d6e57493d'
down_revision: Union[str, Sequence[str], None] = '0afe0368ad31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_promotions', sa.Column('merchant_request_id', sa.String(length=100), nullable=True))
    op.add_column('property_promotions', sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
    op.add_column('property_promotions', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('property_promotions', sa.Column('result_code', sa.String(length=30), nullable=True))
    op.add_column('property_promotions', sa.Column('result_description', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_property_promotions_checkout_request_id'), 'property_promotions', ['checkout_request_id'], unique=False)
    op.create_index(op.f('ix_property_promotions_merchant_request_id'), 'property_promotions', ['merchant_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_promotions_merchant_request_id'), table_name='property_promotions')
    op.drop_index(op.f('ix_property_promotions_checkout_request_id'), table_name='property_promotions')
    op.drop_column('property_promotions', 'result_description')
    op.drop_column('property_promotions', 'result_code')
    op.drop_column('property_promotions', 'phone_number')
    op.drop_column('property_promotions', 'checkout_request_id')
    op.drop_column('property_promotions', 'merchant_request_id')
    # ### end Alembic commands ###