"""create conversations and messages tables

Revision ID: 50e9211a3680
Revises: 8e099e1052dd
Create Date: 2026-09-04 07:25:37.251184
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e9211a3680'
down_revision: Union[str, Sequence[str], None] = '8e099e1052dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('landlord_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_conversations_owner_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_landlord_id'), 'conversations', ['landlord_id'], unique=False)
    op.drop_constraint(op.f('conversations_owner_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['landlord_id'], ['id'], ondelete='CASCADE')
    op.drop_column('conversations', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_owner_id_fkey'), 'conversations', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_conversations_landlord_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_owner_id'), 'conversations', ['owner_id'], unique=False)
    op.drop_column('conversations', 'landlord_id')
    # ### end Alembic commands ###