"""add user verification fields

Revision ID: 6bee123a51d9
Revises: add_cloudinary_public_id
Create Date: 2026-09-28 01:24:23.038740
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bee123a51d9'
down_revision: Union[str, Sequence[str], None] = 'add_cloudinary_public_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "verification_status",
            sa.String(length=30),
            nullable=False,
            server_default="NOT_SUBMITTED",
        ),
    )
    op.add_column('users', sa.Column('verification_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verification_reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verification_notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_verification_status'), 'users', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_status'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_column('users', 'verification_notes')
    op.drop_column('users', 'verification_reviewed_at')
    op.drop_column('users', 'verification_submitted_at')
    op.drop_column('users', 'verification_status')
    # ### end Alembic commands ###