"""create property photos table

Revision ID: ce3c4b6d5728
Revises: 67903fa9c769
Create Date: 2026-08-25 13:20:31.862271
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3c4b6d5728'
down_revision: Union[str, Sequence[str], None] = '67903fa9c769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_photos_id'), 'property_photos', ['id'], unique=False)
    op.create_index(op.f('ix_property_photos_property_id'), 'property_photos', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_photos_property_id'), table_name='property_photos')
    op.drop_index(op.f('ix_property_photos_id'), table_name='property_photos')
    op.drop_table('property_photos')
    # ### end Alembic commands ###